# Generated by Django 5.0.6 on 2024-07-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='profilephoto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='special_files',
            field=models.FileField(blank=True, null=True, upload_to='special_files/'),
        ),
    ]
